// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zqgylhskkbocsjmcrfyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxZ3lsaHNra2JvY3NqbWNyZnlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2OTkyNDYsImV4cCI6MjA5MzI3NTI0Nn0.QXvmVz_H1YXwn8CyBZsVNA0ckYPF4HRJeXNbW-jUE-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
